name: Notify new issue comment

on:
  issue_comment:
    types: [created, edited]

jobs:
  push:

    runs-on: ubuntu-latest

    steps:
    - name: Send Push Notification
      uses: techulus/push-github-action@v0.0.2
      env:
        API_KEY: ${{ secrets.PUSH_API_KEY }}
        MESSAGE: "There is a new comment on blog issue 🤓"
